rules:
  - id: hardcoded-secrets-blocking
    message: "CRITICAL: Secret detected! Remove it from code before merge and REVOKE the key immediately (it is now compromised)."
    severity: ERROR
    languages: [generic]
    patterns:
      - pattern-either:
          # Google API Key
          - pattern-regex: 'AIza[0-9A-Za-z-_]{35}'
          # AWS Access Key
          - pattern-regex: 'AKIA[0-9A-Z]{16}'
          # Stripe Secret Key
          - pattern-regex: 'sk_live_[0-9a-zA-Z]{24}'
          # Firebase API Key
          - pattern-regex: 'AIzaSy[0-9A-Za-z-_]{33}'
          # Slack Webhook
          - pattern-regex: 'https://hooks.slack.com/services/T[a-zA-Z0-9_]+/B[a-zA-Z0-9_]+/[a-zA-Z0-9_]+'
          # Basic passwords
          - pattern-regex: '(?i)(password|secret|token|api_key|apikey)\s*[:=]\s*["''][a-zA-Z0-9!@#$%^&*()_+]{16,}["'']'